name:                pet
version:             0.1.0.0
github:              "fosu/pet"
license:             EULA
author:              "Rose"
maintainer:          "example@example.com"
copyright:           "2017 Rose"

extra-source-files:
- README.md

# Metadata used when publishing your package
synopsis:            A small pet simulation game.
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         A small pet simulation game written in Haskell attempting to adhere to limitations imposed by the Game Boy.

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - sdl2

executables:
  pet:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - mtl
    - transformers
    - filepath
    - containers
    - sdl2
    - pet
